language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: rdI/NdhNAPQBuf9De5zLZr7FTou/92ps6qrog6+MabeSvqbKntmN1s94+ETt0LE13SUaMI2zmzMb9UuNMTKYHePU9KNh1kbpEF0hm05RXgJJw8wezjtH/E41FooWnXCU79wj0hYE4PWuZCx00IR/puoa3ks4j8EoUZ4S1PHeak+SL3fVBfciz6LHUB6BfSSFn3seS7Cb1JpY8Vo1StT33vZl+r4CbnCC7Pkdoc6PvCkJTlGmoCuZ5wTHdmn7uvOY6JTLyxYylvlrB49smuB8G2HCLabC4MUiDZL2/lwUNreeP6xmjDOFC7WCslgZkgxsoNkFpljx++Z7xCLSzCcigOksi2/8maHAn9JjmLZljhoCMpnd+E7OCmKOrCbBb1deBNsnbPQyWOdZ/GZ/Ot8jj6ewm4gQP6bHowcXKOMwy3W19IqvSC0e085O3c/XpfG8Lhn6l5IF1k+PYl9d1m1mKF/xZdCkg7Ny8vPl4jGorzjNEO4UBtKiC58bZmw23bC4MK9LRzfn5vTngn0h/G/qqWNXdQYY7mmEmTo+FSwf2hL08sEWPrYnnRSj9S3t5mnPuGlRUYkIpMgC8Fv3SFMeosZYpEXYVyddcBwg3SFGvCyetxdoypuG3F3OsoHbgrxBoGtQbYlMzrzPFyawNcfhD+zD+rsCq88xm2biICaGJ44=
  - secure: bruovo+aJk0aNH7aLit/b2BxmKoW8KQxGcwmaBJ1NZNuUYy1dPLIRSfuMl9RIunlphZXvT6rj7UKZ0+MsRs9aRQ2qQQSARrIK4w+cDcqfWgcsok+OgpqvT7wCMOdRHkNTS2nsDIxKhU2MsdyJgB3vBkaXqAIuwTLTz2YaABuY3mNDSSJgQZnxNcsiJUmpu/BsvP1O9myijZYmAEsS4gRETm80+jKd3KXwm2JAr4/e6cchNOGSmoNpdMdJY4UrWPmGqXiCHKZSWEnF8b9gP2cuF3a9JuTd1HT5bX5U9s/t6OzemlhdcAHjMvVSfdyE4N9jMuO0BpVNUzV9V1p3/DiaiVdoZRc6GBMjZCFqkJoC73oFd1uicZvyErBBWGWEWpTvlA1TCkbYU+Q1/0I7VBFUEf0LY8FTfgQes60PTiFN06y4roipZsKXiV0OMkhxcFp9a2IMeYskH9WucZOjqxJIS6wfOrcDOJUaSdMm32p1gr53OOlnZ6IpWr2ugNntbocWRL/QKYnE5obaJA1hARe64ev3RJUQv4nGUOxPjSRddVkNRvmtHTilArNOD1eWrygBc5JuYqdooVoEvQgGkVgxHKs744GQ62J3fnlnhu0zF+zKc0BMlNuS3gF8Bdj7FR06cd6GlwKU0FuHJWQwkdCLJyohq4hIbWGMSalX1eH01U=
